# Generated by Django 3.2.5 on 2022-10-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('img_url', models.CharField(max_length=300)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='hvapp.state')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
