# Generated by Django 3.2.5 on 2022-10-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='label',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
