# Generated by Django 3.2.5 on 2022-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvapp', '0002_auto_20221009_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='full_name',
            field=models.CharField(default='full name', max_length=30),
            preserve_default=False,
        ),
    ]
