# Generated by Django 3.2.5 on 2022-10-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hvapp', '0003_state_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='label',
        ),
        migrations.RemoveField(
            model_name='state',
            name='value',
        ),
    ]
