# Generated by Django 3.2.5 on 2022-10-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvapp', '0004_auto_20221010_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='city',
            field=models.CharField(default='city', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.CharField(default='country', max_length=30),
            preserve_default=False,
        ),
    ]
