# Generated by Django 3.2.5 on 2022-10-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hvapp', '0005_auto_20221010_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.AlterField(
            model_name='park',
            name='img_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=2000)),
                ('length', models.CharField(max_length=100)),
                ('elevation_gain', models.CharField(max_length=100)),
                ('map_url', models.CharField(max_length=1000)),
                ('img_url', models.CharField(max_length=1000)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='hvapp.difficulty')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='hvapp.park')),
                ('routetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='hvapp.routetype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=1000)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hvapp.trail')),
            ],
            options={
                'ordering': ['trail'],
            },
        ),
    ]
